# Generated by Django 2.0.2 on 2018-07-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180711_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closeprice',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='currentstat',
            name='symbol',
        ),
        migrations.AddField(
            model_name='symbol',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='symbol',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='market',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='ClosePrice',
        ),
        migrations.DeleteModel(
            name='CurrentStat',
        ),
    ]
