# Generated by Django 2.0.2 on 2018-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180711_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='delta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='symbol',
            name='precent',
            field=models.FloatField(default=0.0),
        ),
    ]
